### ISSUE TITLE
Remove Markdown preconditions on properties that render as literals

### ISSUE THREAD

**Issue by dotCipher** [palantir/roboslack#19]
We have properties that throw errors when building if you provide markdown, but we should actually allow these if they are being rendered as literals in Slack.

We should also have documentation for each of these fields so that users know when to expect any markdown character being rendered as a literal

**Comment by dotCipher** [comment]
Started on PR: https://github.com/palantir/roboslack/pull/16/files#diff-b3f5c61077e4075c4818ab7fd0c300cfL75

**Comment by elektron9** [comment]
Fixed in #21
