### ISSUE TITLE
Artifact is not really published on jcenter

### ISSUE THREAD

**Issue by gionn** [palantir/roboslack#31]
Adding the [README setup snippet](https://github.com/palantir/roboslack#setup) into my gradle project won't work (could not find artifact).

Also searching for roboslack on https://bintray.com/bintray/jcenter won't return any match.

**Comment by dotCipher** [comment]
Thanks for flagging this, I'll take a look into it now.

**Comment by dotCipher** [comment]
Should be fixed in #34

**Comment by dotCipher** [comment]
I verified locally that the example provided in #34 works.  Please reopen this issue or open a new issue if you are still having problems and we can troubleshoot.  Thanks again for flagging this @gionn !
