### ISSUE TITLE
Add support for Markdown in Attachments text/pretext/field fields

### ISSUE THREAD

**Issue by elektron9** [palantir/roboslack#9]
RoboSlack messages with Markdown in Attachment pretext/text/fields fields will not render correctly in Slack. We need to implement the `mrkdwn_in` flag: https://api.slack.com/docs/message-formatting#message_formatting .

**Comment by dotCipher** [comment]
I think it would be sweet to have the builder auto-detect if markdown is being used in these fields and then set the `mrkdwn_in` flag dynamically if they have markdown content

**Comment by elektron9** [comment]
+1, I agree with that option
